name: Seed

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: "ghcr.io/zero-plus-x"
  BACKEND_IMAGE_NAME: "helpua-backend"

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Seed the DB
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: BACKEND_IMAGE_NAME,REGISTRY,GITHUB_SHA
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin ghcr.io
            docker run \
            --name $(echo $BACKEND_IMAGE_NAME)-seed \
            --env DATABASE_URL=${{ secrets.DATABASE_URL }} \
            $(echo $REGISTRY)/$(echo $BACKEND_IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) \
            /bin/sh -c "pnpm install; pnpm run seed"
            docker rm $(echo $BACKEND_IMAGE_NAME)-seed
